# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LivestreamFails' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LivestreamFails
  pod 'Moya'
  pod 'R.swift'
  pod 'RxSwift',    '~> 4.0'
  pod 'RxCocoa',    '~> 4.0'
  pod 'SVProgressHUD'
  pod 'SnapKit'
  pod 'RxDataSources'
  pod 'DZNEmptyDataSet'
  pod 'SwiftSoup'
  
  target 'LivestreamFailsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LivestreamFailsUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
